# See https://stonecutter.kikugie.dev/wiki/config/properties#centralized-properties
mod.id = "molecular"
mod.name = "Molecular"
mod.group = "z3roco01.molecular"
mod.version = "0.0.1"

deps.fabric_loader = "0.19.2"
loomx.loom_version = "1.16-SNAPSHOT"

# lts version
["1.20.1"]
mod.mc_compat = ">=1.20 <=1.20.4"
mod.mc_releases = ["1.20", "1.20.1", "1.20.2", "1.20.3", "1.20.4"]

deps.fabric_api = "0.92.9+1.20.1"

# lts version
["1.21.1"]
mod.mc_compat = ">=1.21 <=1.21.1"
mod.mc_releases = ["1.21", "1.21.1"]

deps.fabric_api = "0.116.10+1.21.1"

# most recent
["26.1"]
mod.mc_compat = ">=26.1"
mod.mc_releases = ["26.1", "26.1.1", "26.1.2"]

deps.fabric_api = "0.145.3+26.1.1"
